### ISSUE TITLE
Declare a license

### ISSUE THREAD

**Issue by morinted** [rsheldiii/openSCAD-projects#1]
Hey there, I was wondering if you would declare a license on this repository.

I previously worked off of your files from Thingiverse.

It's unclear to me whether CC-BY-SA-NC (as you've licensed some materials on Thingiverse) means that you can sell printed versions of the model. Do you have any input on this on what your opinion is for your models in particular?

My modifications were here: https://github.com/morinted/stenomod_case/blob/master/steno_key.scad

**Comment by rsheldiii** [comment]
Hi there!
 I just wanted to let you know that I'm looking in to this. I need to do some research on changing licenses and what exactly noncommercial for an SCAD design would mean. My intention with the keycap library was to make something where attribution would be given but derivatives made with the code can be sold freely, but I wouldn't want that for some of my other designs on here, as I'd like to start selling some of the less general purpose ones myself directly. When I figure things out I'll update the licensing and follow up with you here.

Thanks!
