### ISSUE TITLE
Error applying tutorial to latest version of keys.scad

### ISSUE THREAD

**Issue by seanspotatobusiness** [rsheldiii/openSCAD-projects#14]
I'm using the 08/12/2017 version of keys.scad and I get the following error from the following code. The code was modified from the recently-added tutorial so it should work, I think.

code:
```
cherry() key() {
  translate([-6.25,2.3,-0]) scale(0.074) import("bt_hdst.dxf", inset=true);
};
```
error:
```
Saved backup file: C:/Users/seanv/Documents/OpenSCAD/backups/keys-backup-qHp15184.scad
Compiling design (CSG Tree generation)...
WARNING: Ignoring unknown module 'cherry'. 
Rendering Polygon Mesh using CGAL...
WARNING: No top level geometry to render
```

**Comment by rsheldiii** [comment]
hm... ah, I see the issue. in 8/12 there was no `key()` or `cherry()` function, there was `cherry_key()` instead. if you want to stick with the old version of the script you can try to use that function, though if you upgrade you can use the readme's examples. some of the functionality mentioned in the readme is not available in older versions of the script, so I would recommend updating. if you have git set up it should be as easy as `git pull`!

**Comment by seanspotatobusiness** [comment]
The latest files on Thingiverse are from 08/12/2017 (DD/MM/YYYY). Is that not the best place to get the latest files? I'm talking about key_v2.zip.

**Comment by rsheldiii** [comment]
Ah, that is kind of confusing, I updated the Thingiverse description but haven't updated the code. I'll upload a new version sometime this weekend.

As far as best place to get the latest files, this github repo is the place to be. when I push to Thingiverse I'm just bundling the code on here into a zip file. When V2 is finalized (which should be very, very soon) I'll make a new thing in Thingiverse to limit confusion

**Comment by rsheldiii** [comment]
I believe this is resolved. closing now
