### ISSUE TITLE
It doesn't seem like slop does anything

### ISSUE THREAD

**Issue by thecakeisalie25** [rsheldiii/openSCAD-projects#21]
I created a key model as `sa_row(1) cherry() key();` and one as `sa_row(1) cherry(0.5) key();`. After exporting these models to .stl files however, the files are the exact same, even having the same SHA-256 hashes. In readme.md it says that the default value is 0.3, so the models should be different. Using values other than .5 produce the same result. Am I doing something wrong? Alternatively, is there a way to scale up the default cherry stem, so that the whole stem is bigger?

**Comment by rsheldiii** [comment]
That's a bug related to refactor with `settings.scad` I did recently; special variables that use other special variables won't update when you change the variable they rely on. I'll make a fix for this soon, but in the interim if you change `$stem_slop` in `settings.scad` directly it should work
