### ISSUE TITLE
Stabilizer Types

### ISSUE THREAD

**Issue by wanildopneto** [rsheldiii/openSCAD-projects#24]
Hello,
I'm a newbie when it comes to this kind of stuff but could you please add the option to use different Stabilizer Types?

**Comment by wanildopneto** [comment]
Didn't mean to close it, but ok... e.e'

**Comment by rsheldiii** [comment]
Hi there, welcome to the repo! I'm a bit confused by your request, most stabilizers should already work with the keycaps - I do it in a similar way as real keycaps do, by [adding keystems](https://deskthority.net/w/images/1/12/G80_3000WIN_aspacebar.jpg) at the stabilizer locations. There's an option for rounded keystems that are harder to print, but use less material, if that's what you're looking for. Can you please specify?

thank you!

**Comment by wanildopneto** [comment]
Look, when I try to use the Alps switches instead of cherry... The stabilizers actually change to the Alps switches too.

Em sáb, 19 de mai de 2018 20:44, Bob <notifications@github.com<mailto:notifications@github.com>> escreveu:

Hi there, welcome to the repo! I'm a bit confused by your request, most stabilizers should already work with the keycaps - I do it in a similar way as real keycaps do, by adding keystems<https://deskthority.net/w/images/1/12/G80_3000WIN_aspacebar.jpg> at the stabilizer locations. There's an option for rounded keystems that are harder to print, but use less material, if that's what you're looking for. Can you please specify?

thank you!

**Comment by rsheldiii** [comment]
this should be fixed by https://github.com/rsheldiii/openSCAD-projects/pull/31 , you must now specify a stabilizer type (though the `stabilized()` helper will do that for you). if you need anything else for this let me know!
