### ISSUE TITLE
SA (spherical) keycaps?

### ISSUE THREAD

**Issue by seanspotatobusiness** [rsheldiii/openSCAD-projects#3]
Is it possible to generate ~~SA style key caps (also known as~~ "spherical" keys)? (e.g. [https://i.pinimg.com/originals/36/2e/2f/362e2fda24640449c4568233768b9e87.jpg](url). Thanks.

Edit: I don't know whether the SA key still is not working or whether I just don't understand what an SA keycap is meant to look like! To me, the SA keycap doesn't look much different from the DSA cap (I guess it's just taller?) so maybe I'm actually wanting a particular subtype of SA keycap (the spherical one)?

**Comment by rsheldiii** [comment]
Yep! there are currently no examples in the current version of the script, but here's a test file in the history I accidentally committed: https://github.com/rsheldiii/openSCAD-projects/blob/440b777aea5ac9934b1675b4eaec0ad662549934/key/SAtest.stl that file has minkowski rounding on, so it looks a little nicer than the base keycaps do.

using `keys.scad` you'll need to do something like `sa_row(1) cherry() key()` to get an SA rounded keycap. using `key.scad` changing the `dish_type` to `spherical` will turn on spherical dishing, but you'll have to supply your own measurements (that's what keys.scad is for)
